server:
  port: 8085

#Database Configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bugtracker
    username: regu
    password: regu
  h2:
    console:
      enabled: true
      path: /h2